# docker-compose up -d
version: '3.9'

services:
  database:
    image: postgres:alpine
    container_name: database_dev
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - './.env'
    volumes:
      - pgdata:/data/postgres
    networks:
      - bookdew-dev-network

  adminer_dev:
    image: adminer
    container_name: adminer_dev
    restart: always
    ports:
      - 8080:8080
    networks:
      - bookdew-dev-network

networks:
  bookdew-dev-network:

volumes:
  pgdata:
    driver: local
